### ISSUE TITLE
How to create swc for air?

### ISSUE THREAD

**Issue by feipinxiang** [wise0704/SwcBuild#5]
How to create swc for air?
I use the file and the NativeProcess function to create an air project.

it throw some error like this:
Error: Can not find the type or type is not a compile-time constant: File.

**Comment by wise0704** [comment]
1. Open Project Properties:
![image](https://cloud.githubusercontent.com/assets/13545633/24695012/1b0813ca-1a1f-11e7-88e3-4c294185f06a.png)

2. Set target platform to AIR or AIR Mobile
![image](https://cloud.githubusercontent.com/assets/13545633/24695044/34178148-1a1f-11e7-829f-a7978c638605.png)

**Comment by feipinxiang** [comment]
thx.This saves me a lot of time. Thank you for your work.

**Comment by wise0704** [comment]
You're welcome :)
