### ISSUE TITLE
the project name not support chinaese

### ISSUE THREAD

**Issue by feipinxiang** [wise0704/SwcBuild#6]
If I create a swcBuild project with a Chinese name, I will get a file named ".as" instead of "projectName.as" in the src folder.

Not a big thing, I will create an English name project in the future. ^-^
I know that the name is swc file name, but the ".as" file does not appear in fd.If I want to change its name, I have to use Windows File Manager. If the Chinese name project can be generated with a default "main.as" file is fantastic, like fd default project.

![2017-04-17_165359](https://cloud.githubusercontent.com/assets/2398548/25084438/f701f706-238e-11e7-847a-95e687d362ca.png)

**Comment by wise0704** [comment]
Unfortunately, it's rather a problem with FD than this extension.
`$(ProjectID)` is used for the initial .as file and the output .swf file, and the variable only allows valid identifiers.
Without this extension turning into a plugin and having access to the code, there is no way, as far as I'm aware of, to separately deal with cases where `$(ProjectID) == ""`.

You've suggested as a possible solution that using "Main.as" instead would solve this. However it still poses 2 problems:
 - the output file will still have an empty file name: ".swc"
 - an AS3 library project does not have a concept of "main"/"document" class

You can try raising an issue at https://github.com/fdorg/flashdevelop/issues.
